---
title: "R Notebook"
output: html_notebook
---

Laboratorio 1 

1 Vectores y matrices

1.1
```{r}
student_1 = c(50.4, 62.3, 92.1, 77.6, TRUE) 
student_2 = c(41.7, 87.9, 75.3, 72.4, FALSE) 
student_3 = c(30.3, 67.8, 69.3, 71.2, FALSE) 
student_4 = c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 = c(70.4, 88.2, 95.2, 90.7, TRUE)
```

1.2 
```{r}
students_vector <- c(student_1,student_2,student_3,student_4,student_5)
```

1.3
```{r}
students_matrix <- matrix(students_vector, nrow=5, byrow = TRUE)
students_matrix
```

2.1
```{r}
name_students <- c( "Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones","Tom Hill")
name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics","Legal_age")
name_students
name_courses_legal_age
```

2.2

```{r}
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students
students_matrix
```
3.1

```{r}
total_grade_student <- rowSums(students_matrix[,1:4])
total_grade_student
```

3.2

```{r}
result_students <-cbind(students_matrix, total_grade_student)
result_students
```

4.1

```{r}

selected_elements <- result_students[c(1,3,4), c(2,4)]
print(selected_elements)

```

5.1

```{r}
students_grades_df <- as.data.frame(result_students)
students_grades_df
```

5.2
**Nota, cuando se crearon los vectores al principio, ya que estos solo pueden tener un tipo de valor, 
automáticamente TRUE y FALSE se convirtieron en 1 y 0 respectivamente, por eso se utiliza esta condición
```{r}
subset(students_grades_df, students_grades_df$Accounting>80 & students_grades_df$Legal_age==1)
```

6.1
```{r}

students_projection <- function(df, nRows, nCols){
  for(i in 1:nRows){
    for(j in 1:nCols){
      if(df[i, j] <= 45){
        print("Student at risk")
      } else if (df[i, j] < 61 & df[i, j] > 45){
        print("Student may be approved")
      } else {
        print("Student approved")
      }
    }
  }
}

```

6.2

```{r}
students_projection(students_grades_df, 5, 4)
```

